### ISSUE TITLE
readme里的A站地址错啦。

### ISSUE THREAD

**Issue by EscapeB** [OpenDanmakuCommunity/awesome-danmaku#4]
应该是https://www.acfun.cn =.=

**Comment by jabbany** [comment]
嘛，当时文档制作的时候还是 .tv 呢 https://en.wikipedia.org/wiki/AcFun#:~:text=The%20website%20changed%20its%20domain%20from%20acfun.cn%20to%20acfun.tv.

**Comment by jabbany** [comment]
已patch
